---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: gantsign.visual-studio-code
      when: configure_vscode
      tags: ['vscode']
      users:
        - username: ger
          visual_studio_code_extensions:
            - hashicorp.terraform
            - hediet.vscode-drawio
            - redhat.vscode-yaml
            - ms-vscode-remote.remote-wsl
            - ms-vscode-remote.remote-containers
            - ms-vscode.remote-explorer
            - ms-vscode.remote-server
            - ms-vscode-remote.remote-ssh
            - ms-azuretools.vscode-docker
            - ms-vscode-remote.vscode-remote-extensionpack
          # visual_studio_code_settings_overwrite: true
          # visual_studio_code_settings: {
          #   "editor.rulers": [80, 100, 120],
          #   "editor.renderWhitespace": true,
          #   "files.associations": {
          #     "Vagrantfile": "ruby"
          #   }
          # }
          # visual_studio_code_keybindings_overwrite: true
          # visual_studio_code_keybindings: [
          #   {
          #     "key":     "ctrl+'",
          #     "command": "workbench.action.terminal.focus"
          #   },
          #   {
          #     "key":     "ctrl+'",
          #     "command": "workbench.action.focusActiveEditorGroup",
          #     "when":    "terminalFocus"
          #   }
          # ]

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
